# Generated by Django 3.2.4 on 2021-06-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savenow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savenow',
            name='body',
        ),
        migrations.RemoveField(
            model_name='savenow',
            name='title',
        ),
        migrations.AddField(
            model_name='savenow',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=False, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='savenow',
            name='name',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savenow',
            name='purpose',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
    ]
