# Generated by Django 3.2.4 on 2021-06-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savenow', '0002_auto_20210629_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=5, default=False, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='savenow',
            old_name='created_at',
            new_name='saved_at',
        ),
    ]
